(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
const FILE=(name)=>`https://commons.wikimedia.org/wiki/Special:FilePath/${encodeURIComponent(name)}?width=1200`;
const FALLBACKS=[FILE('Paisaje de los Llanos Orientales colombianos.jpg'),FILE('Puerto Carreño, Vichada, Colombia - panoramio.jpg')];
const makeImage=(src,alt,fallback=FALLBACKS[0])=>{const img=document.createElement('img');img.src=src;img.alt=alt;img.loading='lazy';img.decoding='async';img.addEventListener('error',()=>{if(img.dataset.retry!=='1'&&fallback){img.dataset.retry='1';img.src=fallback}else{img.classList.add('image-failed');img.removeAttribute('src')}},{once:false});return img};
const tile=(name,alt,title,text,fallback)=>{const f=document.createElement('figure');f.className='extra-visual-tile scroll-reveal';f.append(makeImage(FILE(name),alt,fallback));const cap=document.createElement('figcaption');const b=document.createElement('b');b.textContent=title;const s=document.createElement('span');s.textContent=text;cap.append(b,s);f.append(cap);return f};
const gallery=(id,title,items)=>{const section=$(id);if(!section||$('.extra-visual-block',section))return;const block=document.createElement('div');block.className='container extra-visual-block';const h=document.createElement('h3');h.textContent=title;h.className='extra-visual-heading scroll-reveal';const grid=document.createElement('div');grid.className='extra-visual-grid';items.forEach(x=>grid.append(tile(...x)));block.append(h,grid);const anchor=section.querySelector('.container:last-of-type');(anchor||section).after(block)};
const addClickableDetails=()=>{const items=[
['.nature-card:nth-child(1)','Piedemonte y llanuras','El relieve cambia desde el piedemonte cercano a la cordillera Oriental hasta grandes superficies de sabana y altillanura. Esa transición ayuda a entender los cambios de suelos, vegetación y actividades humanas.'],
['.nature-card:nth-child(2)','Lluvia y sequía','La alternancia entre temporadas húmedas y secas modifica el nivel de ríos, esteros y humedales. También influye en los cultivos, los pastos, la movilidad y las actividades del campo.'],
['.nature-card:nth-child(3)','Una red de ríos','Los ríos Meta, Arauca, Casanare y Guaviare conectan paisajes y comunidades. Además de su valor ecológico, algunos funcionan como rutas de transporte y sostienen actividades locales.'],
['.people-grid article:nth-child(1)','Ciudades como puntos de conexión','Villavicencio, Yopal, Arauca y Puerto Carreño cumplen funciones urbanas diferentes: concentran servicios, comercio, educación, transporte y conexiones con zonas rurales.'],
['.people-grid article:nth-child(2)','Campo, sabana y trabajo','La vida rural depende bastante del clima, el agua, los suelos y las vías. Por eso los cambios ambientales pueden sentirse directamente en el trabajo y en la vida cotidiana.'],
['.culture-list > div:nth-child(1)','Música y danza','El joropo reúne música, canto y danza. Entre sus instrumentos aparecen el arpa llanera, el cuatro, las maracas y otros instrumentos según el conjunto. La tradición se transmite entre generaciones y sigue incorporando nuevas propuestas.'],
['.culture-list > div:nth-child(2)','Gastronomía','La cocina llanera está relacionada con la vida rural y con productos disponibles en el territorio. Un ejemplo muy conocido es la carne a la llanera o mamona, además de preparaciones con arroz, yuca, plátano y otros productos. La comida también funciona como memoria cultural.'],
['.culture-list > div:nth-child(3)','Tradición oral','Las coplas, relatos, refranes y memorias permiten transmitir conocimientos y experiencias. La oralidad conserva historias locales y ayuda a que las nuevas generaciones conozcan expresiones propias de sus comunidades.'],
['.culture-list > div:nth-child(4)','Trabajo del llano','Los oficios rurales reúnen habilidades, herramientas, lenguaje y conocimiento del paisaje. Muchas prácticas se aprenden observando y acompañando a otras personas, por lo que también forman parte del patrimonio cultural.'],
['.economy-cards article:nth-child(1)','Sector primario','Incluye actividades directamente relacionadas con el territorio, como agricultura y ganadería. En algunos departamentos también tiene importancia la extracción de hidrocarburos.'],
['.economy-cards article:nth-child(2)','Sector secundario','Comprende actividades que transforman materias primas. Así, la economía continúa después de producir un cultivo o extraer un recurso, mediante procesos de transformación y elaboración.'],
['.economy-cards article:nth-child(3)','Sector terciario','Comercio, transporte, educación, administración, restaurantes, alojamiento y turismo son servicios que conectan personas, productos y territorios.']
];items.forEach(([sel,title,text])=>{$$(sel).forEach(card=>{if(card.dataset.expandReady)return;card.dataset.expandReady='1';card.classList.add('click-expand-card');card.setAttribute('role','button');card.setAttribute('tabindex','0');const panel=document.createElement('div');panel.className='click-expand-panel';const h=document.createElement('h4');h.textContent=title;const p=document.createElement('p');p.textContent=text;panel.append(h,p);card.append(panel);const toggle=()=>card.classList.toggle('is-expanded');card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;toggle()});card.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();toggle()}})})})};
const addPresentationViewer=()=>{const section=$('#presentacion');const card=$('.presentation-card',section);if(!section||!card||$('.presentation-viewer',section))return;const raw='https://raw.githubusercontent.com/Juangema07/Descubriendo-la-Orinoqu-a/main/REGI%C3%93N%20ORINOQU%C3%8DA.pptx';const viewer=document.createElement('div');viewer.className='container presentation-viewer scroll-reveal';const h=document.createElement('h3');h.textContent='Mira y pasa las diapositivas aquí';const p=document.createElement('p');p.textContent='El visor queda dentro de la página. Si el navegador no muestra los controles, usa “Abrir archivo” para verlo directamente.';const frame=document.createElement('iframe');frame.className='ppt-frame';frame.src='https://view.officeapps.live.com/op/embed.aspx?src='+encodeURIComponent(raw);frame.title='Presentación de la Región Orinoquía';frame.loading='eager';frame.referrerPolicy='no-referrer';frame.setAttribute('allowfullscreen','');viewer.append(h,p,frame);const actions=document.createElement('div');actions.className='viewer-actions';const open=document.createElement('a');open.className='repo-ppt';open.href=raw;open.target='_blank';open.rel='noopener noreferrer';open.textContent='Abrir archivo';const download=document.createElement('a');download.className='download-ppt';download.href=raw;download.setAttribute('download','REGIÓN ORINOQUÍA.pptx');download.textContent='Descargar PowerPoint ↓';actions.append(open,download);viewer.append(actions);card.after(viewer)};
const scroll=()=>{const items=$$('.section > .container, .photo-break, .visual-card, .nature-card, .people-grid article, .culture-list > div, .economy-cards article, .challenge-grid details, .park-grid article, .game-card, .extra-visual-tile, .info-expansion');items.forEach((el,i)=>{el.classList.add('scroll-reveal');el.style.setProperty('--reveal-delay',`${Math.min(i%6,5)*55}ms`)});if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('is-visible');io.unobserve(e.target)}}),{threshold:.08,rootMargin:'0px 0px -35px 0px'});items.forEach(x=>io.observe(x))}else items.forEach(x=>x.classList.add('is-visible'))};
const init=()=>{
gallery('#territorio','La región también se entiende mirando el territorio',[
['Mapa_de_Colombia_(región_de_la_Orinoquía).svg','Mapa de la Orinoquía colombiana','Ubicación','Una ayuda visual para ubicar la región hacia el oriente del país.',FILE('Paisaje de los Llanos Orientales colombianos.jpg')],
['Puerto Carreño, Vichada - panoramio.jpg','Vista panorámica de Puerto Carreño','Vichada','Una ciudad ubicada junto al río Orinoco.',FILE('Cerro La Bandera, Puerto Carreño - panoramio.jpg')],
['Rio Orinoco, Puerto Carreño - panoramio.jpg','Río Orinoco en Puerto Carreño','Río Orinoco','El gran río ayuda a entender la conexión hidrográfica de la región.',FILE('Paisaje de los Llanos Orientales colombianos.jpg')]]);
gallery('#naturaleza','Paisajes diferentes dentro de una misma región',[
['Cuenca_Rio_Cravo_Sur.jpg','Cuenca del río Cravo Sur','Ríos y relieve','Los cursos de agua ayudan a explicar cómo se organiza el paisaje.'],
['Perdidos_en_la_sabana.jpg','Paisaje de sabana','Sabana','Las sabanas son uno de los ambientes más representativos de los Llanos.'],
['Morichal_en_La_Primavera,_Vichada.jpg','Morichal en La Primavera','Humedales y palmas','Los morichales están asociados a ambientes donde el agua tiene un papel importante.']]);
gallery('#biodiversidad','Fauna y flora para mirar con otros ojos',[
['Curiosidad_en_el_Dosel,_Mono_Maicero_de_la_Orinoquía.png','Mono maicero de la Orinoquía','Mamíferos','Los bosques y corredores de vegetación ofrecen refugio y alimento.'],
['Melanerpes_cruentatus_Little_Woodpecker.png','Carpinterito','Aves','Las aves permiten observar la variedad de ambientes del territorio.'],
['Racimo_de_la_palmera_corneto.jpg','Palmera corneto','Flora','La vegetación es parte esencial de las redes ecológicas.']]);
gallery('#gente','Personas, ciudades y formas de conectar el territorio',[
['Navegabilidad_por_el_Río_Meta.jpg','Navegación por el río Meta','Conectividad','El transporte fluvial puede conectar comunidades y actividades.'],
['Calle_principal_de_Puerto_Carreño_-_panoramio.jpg','Calle principal de Puerto Carreño','Vida urbana','La vida urbana también hace parte de la diversidad territorial.'],
['Panamá_de_Arauca,_Arauquita-Col.jpg','Arauquita, Arauca','Arauca','Una muestra del territorio y de sus poblaciones.']]);
gallery('#cultura','Imágenes para entender la cultura llanera',[
['Pareja_bailando_joropo_llanero_(Puro).jpg','Pareja bailando joropo llanero','Música y danza','El joropo combina música y baile y es una expresión cultural muy reconocida.'],
['Arpa,_cuatro,_maracas,_bajo_y_animador..jpg','Instrumentos de un conjunto de joropo','Música','Arpa, cuatro y maracas son instrumentos asociados a distintas agrupaciones de música llanera.'],
['Carne_a_la_llanera,_conocida_como_mamona..jpg','Carne a la llanera o mamona','Gastronomía','Una preparación muy reconocida de la cocina llanera.',FILE('Paisaje de los Llanos Orientales colombianos.jpg')]]);
gallery('#economia','Producción, agricultura y territorio',[
['Llanos_Orientales_-_Arroz.jpg','Arroz en los Llanos Orientales','Agricultura','Los cultivos forman parte de la actividad agropecuaria.'],
['Hacienda_de_Cumaral.jpg','Hacienda de Cumaral','Actividad rural','Los espacios rurales muestran otra dimensión del paisaje productivo.'],
['Los_Llanos_Colombia_by_David.png','Paisaje de Los Llanos','Territorio productivo','Producción, espacio y naturaleza se relacionan en el territorio.']]);
gallery('#retos','Cambios del territorio que vale la pena observar',[
['Bajo_llanura_inundada_en_La_Primavera,_Vichada.jpg','Llanura inundada en Vichada','Agua','Las temporadas húmedas cambian temporalmente el paisaje.'],
['Morichal_en_La_Primavera,_Vichada.jpg','Morichal en La Primavera','Ecosistemas','Estos ambientes asociados al agua necesitan manejo y conservación.'],
['NP_Llanos27_lo_(5853938480).jpg','Paisaje de los Llanos','Transformación','Mirar el paisaje permite conversar sobre los cambios del territorio.']]);
gallery('.parks','Áreas naturales y paisajes protegidos',[
['TuparroNPP_banner.jpg','Paisaje de El Tuparro','Vichada','Un área protegida de gran importancia natural.'],
['PNN_Sierra_de_la_Macarena.jpg','Sierra de La Macarena','Meta','Un territorio de gran diversidad ambiental y paisajística.']]);
addClickableDetails();addPresentationViewer();scroll();
};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();