(()=>{'use strict';
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const safeGet=(k,d='')=>{try{return localStorage.getItem(k)??d}catch{return d}};
const safeSet=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};
window.addEventListener('load',()=>setTimeout(()=>$('#loader')?.classList.add('done'),250),{once:true});
const nav=$('#navLinks'),menu=$('#menuBtn');
menu?.addEventListener('click',()=>{const open=nav.classList.toggle('mobile-open');menu.setAttribute('aria-expanded',String(open))});
$$('#navLinks a').forEach(a=>a.addEventListener('click',()=>{nav?.classList.remove('mobile-open');menu?.setAttribute('aria-expanded','false')}));
const deptData={meta:['Meta · Villavicencio','Es uno de los principales accesos a los Llanos y combina piedemonte, sabanas, actividades agropecuarias, servicios y espacios naturales como la Sierra de La Macarena.'],casanare:['Casanare · Yopal','Tiene una fuerte relación histórica con la ganadería, la agricultura y la explotación de hidrocarburos, además de una amplia zona de sabanas.'],arauca:['Arauca · Arauca','Se ubica al norte de la región y combina piedemonte, llanura y una importante relación fronteriza con Venezuela.'],vichada:['Vichada · Puerto Carreño','Es un territorio de grandes extensiones de sabana y bosques, relacionado con ríos como el Orinoco y el Meta y con áreas de conservación.']};
const renderDept=k=>{const d=deptData[k]||deptData.meta,b=$('#deptInfo');if(!b)return;b.replaceChildren();const h=document.createElement('h3'),p=document.createElement('p');h.textContent=d[0];p.textContent=d[1];b.append(h,p)};
$$('.dept').forEach(b=>b.addEventListener('click',()=>{$$('.dept').forEach(x=>x.classList.remove('active'));b.classList.add('active');renderDept(b.dataset.dept)}));renderDept('meta');
const bestKey='ruta-best-score';const updateBest=s=>{const old=Number(safeGet(bestKey,'0'));if(s>old)safeSet(bestKey,String(s));const b=$('#bestScore');if(b)b.textContent=`Mejor puntaje: ${Math.max(old,s)} pts`};updateBest(0);
const quiz=[
 ['¿Qué departamentos forman el recorte escolar principal usado en esta web?',['Meta, Casanare, Arauca y Vichada','Nariño, Huila, Tolima y Meta','Bolívar, Sucre, Córdoba y Arauca'],0],
 ['¿Qué gran cuenca se relaciona con la Orinoquía?',['Amazonas','Orinoco','Magdalena'],1],
 ['¿Cuál es un ambiente característico de varios sectores llaneros?',['Sabana','Páramo urbano','Arrecife coralino'],0],
 ['¿Qué factor cambia mucho entre temporadas y afecta al territorio?',['El nivel del agua','La ubicación de Colombia','La forma de la cordillera'],0],
 ['¿Cuál pertenece al sector primario?',['Ganadería','Hotelería','Transporte'],0],
 ['¿Cuál es una expresión cultural reconocida de la región?',['Joropo','Mapalé del Caribe','Sanjuanero huilense'],0],
 ['¿En qué departamento está principalmente la Sierra de La Macarena?',['Meta','Casanare','Vichada'],0],
 ['¿Qué idea resume mejor un reto regional?',['Producir sin límites','Equilibrar desarrollo y conservación','Eliminar toda actividad económica'],1]
];
let qi=0,qScore=0,qStreak=0,qTimer=null,qStarted=false,qAnswered=false,qTime=60;
const renderQuiz=()=>{const box=$('#quizBox'),progress=$('#quizProgress');if(!box)return;box.replaceChildren();qAnswered=false;const d=quiz[qi];progress.textContent=`Pregunta ${qi+1} de ${quiz.length} · Racha ${qStreak}`;const q=document.createElement('p');q.textContent=d[0];q.style.fontWeight='800';box.append(q);d[1].forEach((txt,i)=>{const b=document.createElement('button');b.className='quiz-option';b.type='button';b.textContent=txt;b.addEventListener('click',()=>answerQuiz(i,b));box.append(b)});if(!qStarted)startTimer()};
const answerQuiz=(i,b)=>{if(qAnswered)return;qAnswered=true;$$('.quiz-option',$('#quizBox')).forEach(x=>x.disabled=true);const d=quiz[qi],ok=i===d[2];b.classList.add(ok?'correct':'wrong');if(!ok)$(`.quiz-option:nth-of-type(${d[2]+1})`,$('#quizBox'))?.classList.add('correct');const r=$('#quizResult');if(ok){qStreak++;qScore+=10+(qStreak-1)*2;r.textContent=`✓ Correcto. +${10+(qStreak-1)*2} puntos. ¡Racha de ${qStreak}!`}else{qStreak=0;r.textContent=`No exactamente. La respuesta correcta era: ${d[1][d[2]]}.`};$('#quizScore').textContent=`${qScore} pts`;updateBest(qScore);const next=document.createElement('button');next.className='next-action';next.type='button';next.textContent=qi<quiz.length-1?'Siguiente pregunta':'Terminar reto';next.addEventListener('click',()=>{if(qi<quiz.length-1){qi++;renderQuiz()}else finishQuiz()});$('#quizBox').append(next)};
const startTimer=()=>{qStarted=true;qTime=60;const bar=$('#timerBar'),txt=$('#timerText');if(qTimer)clearInterval(qTimer);qTimer=setInterval(()=>{qTime--;txt.textContent=qTime;bar.style.width=`${qTime/60*100}%`;if(qTime<=0){clearInterval(qTimer);finishQuiz(true)}},1000)};
const finishQuiz=timeUp=>{if(qTimer)clearInterval(qTimer);qStarted=false;const box=$('#quizBox');box.replaceChildren();const p=document.createElement('p');p.className='game-result';p.textContent=timeUp?`⏱️ Se acabó el tiempo. Puntaje: ${qScore}.`:`🏁 Reto terminado: ${qScore} puntos de ${quiz.length*10}+ bonificación por racha.`;box.append(p);const again=document.createElement('button');again.className='next-action';again.textContent='Jugar otra vez';again.addEventListener('click',resetQuiz);box.append(again);$('#quizResult').textContent='';updateBest(qScore)};
const resetQuiz=()=>{if(qTimer)clearInterval(qTimer);qi=0;qScore=0;qStreak=0;qStarted=false;$('#quizScore').textContent='0 pts';$('#timerText').textContent='60';$('#timerBar').style.width='100%';renderQuiz()};renderQuiz();
const pairs=[['Meta','Departamento'],['Orinoco','Río / cuenca'],['Joropo','Cultura'],['Ganadería','Sector primario'],['El Tuparro','Área protegida'],['Morichal','Ecosistema']];
let selected=null,matched=0;
const renderMatch=()=>{const box=$('#matchingGame');if(!box)return;box.replaceChildren();const items=[];pairs.forEach((p,i)=>{items.push({text:p[0],key:i,type:'a'});items.push({text:p[1],key:i,type:'b'})});items.sort(()=>Math.random()-.5);items.forEach(x=>{const b=document.createElement('button');b.type='button';b.className='match-item';b.textContent=x.text;b.dataset.key=x.key;b.dataset.type=x.type;b.addEventListener('click',()=>matchPick(b));box.append(b)});$('#matchScore').textContent=`${matched}/6`};
const matchPick=b=>{if(b.classList.contains('matched'))return;if(!selected){selected=b;b.classList.add('selected');return}if(selected===b)return;if(selected.dataset.key===b.dataset.key&&selected.dataset.type!==b.dataset.type){selected.classList.remove('selected');selected.classList.add('matched');b.classList.add('matched');matched++;$('#matchScore').textContent=`${matched}/6`;$('#matchResult').textContent=matched===6?'🎉 ¡Conexión completa! +60 puntos.':'✓ Bien. Sigue con la siguiente conexión.';updateBest(matched*10)}else{b.classList.add('selected');$('#matchResult').textContent='Casi. Esa pareja no corresponde. Prueba otra combinación.';setTimeout(()=>{b.classList.remove('selected');selected?.classList.remove('selected');selected=null},500);return}selected=null};
$('#resetMatch')?.addEventListener('click',()=>{selected=null;matched=0;$('#matchResult').textContent='';renderMatch()});renderMatch();
const cases=[
 ['Una zona baja se llena de agua durante la temporada de lluvias. ¿Qué estás observando?',['Un estero o ambiente inundable','Una zona industrial','Un arrecife'],0],
 ['Encuentras una actividad dedicada a criar ganado y producir alimentos del campo. ¿Qué sector predomina?',['Primario','Secundario','Terciario'],0],
 ['Una ciudad concentra comercio, educación, transporte y restaurantes. ¿Qué función económica destaca?',['Servicios','Extracción minera','Cultivo'],0],
 ['Una zona protegida busca conservar sabanas, ríos y biodiversidad. ¿Cuál es la idea principal?',['Conservación','Urbanización total','Eliminar los ríos'],0],
 ['Una expresión combina música, canto y baile y es muy reconocida en los Llanos. ¿Cuál?',['Joropo','Vallenato','Bambuco'],0]
];let ci=0,cScore=0;
const renderCase=()=>{const text=$('#caseText'),box=$('#caseOptions');if(!text||!box)return;box.replaceChildren();const d=cases[ci];text.textContent=d[0];d[1].forEach((x,i)=>{const b=document.createElement('button');b.className='case-option';b.type='button';b.textContent=x;b.addEventListener('click',()=>answerCase(i,b));box.append(b)})};
const answerCase=(i,b)=>{const d=cases[ci];$$('.case-option',$('#caseOptions')).forEach(x=>x.disabled=true);const ok=i===d[2];b.classList.add(ok?'correct':'wrong');if(!ok)$(`.case-option:nth-child(${d[2]+1})`,$('#caseOptions'))?.classList.add('correct');if(ok){cScore+=20;$('#caseResult').textContent='✓ Caso resuelto. +20 puntos.'}else $('#caseResult').textContent=`Pista fallida. La mejor respuesta era: ${d[1][d[2]]}.`;$('#caseScore').textContent=`${cScore} pts`;updateBest(cScore);const n=document.createElement('button');n.className='small-action';n.textContent=ci<cases.length-1?'Siguiente caso':'Ver resultado';n.addEventListener('click',()=>{if(ci<cases.length-1){ci++;$('#caseResult').textContent='';renderCase()}else{renderCase();$('#caseResult').textContent=`🕵️ Investigación terminada: ${cScore} puntos.`}});$('#caseOptions').append(n)};renderCase();
$('#resetGames')?.addEventListener('click',()=>{try{localStorage.removeItem(bestKey)}catch{}updateBest(0);$('#bestScore').textContent='Mejor puntaje: 0 pts'});
const reveal=$$('.reveal');if('IntersectionObserver'in window){const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});reveal.forEach(x=>io.observe(x))}else reveal.forEach(x=>x.classList.add('visible'));

/* Mejoras visuales: mapa real, galería temática, línea de recorrido y PowerPoint visible. */
const loadVisualCSS=()=>{if($('#visualUpgradesCSS'))return;const link=document.createElement('link');link.id='visualUpgradesCSS';link.rel='stylesheet';link.href='visual-upgrades.css';document.head.append(link)};
const img=(src,alt)=>{const el=document.createElement('img');el.src=src;el.alt=alt;el.loading='lazy';el.decoding='async';return el};
const visualCard=(src,alt,title,text)=>{const figure=document.createElement('figure');figure.className='visual-tile';figure.append(img(src,alt));const cap=document.createElement('figcaption'),b=document.createElement('b'),s=document.createElement('span');b.textContent=title;s.textContent=text;cap.append(b,s);figure.append(cap);return figure};
const addTerritoryMap=()=>{const old=$('.fake-map'),panel=old?.closest('.map-panel');if(!panel||$('.visual-map-card',panel))return;const card=document.createElement('div');card.className='visual-map-card';const media=document.createElement('div');media.className='visual-map-media';media.append(img('https://upload.wikimedia.org/wikipedia/commons/1/16/Mapa_de_Colombia_%28regi%C3%B3n_de_la_Orinoqu%C3%ADa%29.svg','Mapa de Colombia con la región de la Orinoquía resaltada'));const copy=document.createElement('div');copy.className='visual-map-copy';const k=document.createElement('p');k.className='map-kicker';k.textContent='MAPA DE UBICACIÓN';const h=document.createElement('h3');h.textContent='La Orinoquía está al oriente de Colombia.';const p=document.createElement('p');p.textContent='Este mapa permite ubicar visualmente la región antes de entrar en sus paisajes, departamentos y ecosistemas.';const ul=document.createElement('ul');ul.className='map-points';[['Meta','Villavicencio'],['Casanare','Yopal'],['Arauca','Arauca'],['Vichada','Puerto Carreño']].forEach(([a,b])=>{const li=document.createElement('li');li.textContent=`${a} · ${b}`;ul.append(li)});const src=document.createElement('p');src.className='map-source';src.textContent='Mapa: Wikimedia Commons · Milenioscuro · CC BY-SA 4.0.';copy.append(k,h,p,ul,src);card.append(media,copy);old.replaceWith(card);const mt=$('.map-text',panel);mt?.remove()};
const addVisualGallery=()=>{if($('.visual-strip'))return;const anchor=$('#naturaleza');if(!anchor)return;const wrap=document.createElement('div');wrap.className='container visual-strip';wrap.append(visualCard('https://upload.wikimedia.org/wikipedia/commons/f/f9/PNN_Sierra_de_la_Macarena.jpg','Paisaje del Parque Nacional Natural Sierra de La Macarena','Sierra de La Macarena','Un paisaje que muestra la transición entre agua, roca y vegetación en Meta.'),visualCard('https://upload.wikimedia.org/wikipedia/commons/c/c4/CA%C3%91O_CRISTALES_%E2%80%93_SIERRA_DE_LA_MACARENA.jpg','Caño Cristales en la Sierra de La Macarena','Caño Cristales','Un ejemplo visual de la riqueza natural de la Sierra de La Macarena.'),visualCard('https://upload.wikimedia.org/wikipedia/commons/0/02/%22Bajo%22_llanura_inundada_en_La_Primavera%2C_Vichada.jpg','Llanura inundada en La Primavera, Vichada','Llanura inundable','El agua cambia el aspecto del paisaje según la temporada.'));const heading=document.createElement('div');heading.className='container';const h=document.createElement('h3');h.textContent='Tres postales para entender el territorio';h.style.margin='30px 0 0';heading.append(h);anchor.append(heading,wrap)};
const addVisualTimeline=()=>{if($('.visual-timeline'))return;const anchor=$('#gente');if(!anchor)return;const box=document.createElement('div');box.className='container visual-timeline';[['01','Piedemonte','Relieve cercano a la cordillera Oriental.'],['02','Sabana','Grandes superficies abiertas y dinámicas estacionales.'],['03','Humedales','Esteros, morichales y zonas inundables.'],['04','Ríos','Conectan ecosistemas, poblaciones y actividades.']].forEach(([n,t,d])=>{const article=document.createElement('article');article.className='timeline-step';const b=document.createElement('b');b.textContent=n;const strong=document.createElement('strong');strong.textContent=t;const span=document.createElement('span');span.textContent=d;article.append(b,strong,span);box.append(article)});anchor.querySelector('.container.people-grid')?.after(box)};
const addPresentation=()=>{if($('#presentacion'))return;const games=$('#juegos');if(!games)return;const section=document.createElement('section');section.id='presentacion';section.className='section';const container=document.createElement('div');container.className='container';const card=document.createElement('article');card.className='presentation-card';const copy=document.createElement('div');copy.className='presentation-copy';const k=document.createElement('div');k.className='eyebrow-vu';k.textContent='11 · PRESENTACIÓN';const h=document.createElement('h3');h.textContent='¿Buscas el PowerPoint? Aquí está.';const p=document.createElement('p');p.textContent='La presentación de la Región Orinoquía ya está guardada en el repositorio. Desde aquí puedes descargarla directamente o abrir su archivo en GitHub.';const actions=document.createElement('div');actions.className='presentation-actions';const dl=document.createElement('a');dl.className='download-ppt';dl.href='REGIÓN%20ORINOQUÍA.pptx';dl.setAttribute('download','REGIÓN ORINOQUÍA.pptx');dl.textContent='Descargar PowerPoint ↓';const repo=document.createElement('a');repo.className='repo-ppt';repo.href='REGIÓN%20ORINOQUÍA.pptx';repo.textContent='Abrir archivo →';actions.append(dl,repo);copy.append(k,h,p,actions);const preview=document.createElement('div');preview.className='slide-preview';const stack=document.createElement('div');stack.className='slide-stack';['ORINOQUÍA','TERRITORIO','CULTURA · NATURALEZA · ECONOMÍA'].forEach(t=>{const s=document.createElement('span');s.textContent=t;stack.append(s)});preview.append(stack);card.append(copy,preview);container.append(card);section.append(container);games.before(section);};
const addPresentationNav=()=>{if(!nav||$('#presentacionLink'))return;const a=document.createElement('a');a.id='presentacionLink';a.href='#presentacion';a.textContent='Presentación';nav.append(a)};
loadVisualCSS();addTerritoryMap();addVisualGallery();addVisualTimeline();addPresentation();addPresentationNav();
})();